export const SWORD_HIT_RADIUS = 0.32;
export const FOCUS_PIERCING_HEIGHT = 1.65;
export const FUSION_BODY_HEIGHT = 0.72;
export const FUSION_HIT_RADIUS = 0.88;
export const FUSION_CONTACT_COOLDOWN_TICKS = 30;
export const PLAYER_MOVEMENT_ACCELERATION = 48;
export const PLAYER_MOVEMENT_ARRIVAL_RADIUS = 0.04;
