/** 不稳定的底层 API；内部 Post 阶段与迁移实现仍保持私有。 */
export * from "./index";
export * from "./storage";
export { ResourceContainer } from "./context/resource";
export { ServiceContainer } from "./context/service";
export { StateContainer } from "./context/state";
export { CoreEcsModule } from "./ecs/core-module";
export { EntityCommand } from "./ecs/command/entity-command";
export type { CommandSubmit, CommandType } from "./ecs/command/command";
export * from "./ecs/memory";
export { Archetype, ENTITY_COLUMN } from "./ecs/archetype/archetype";
export type { ArchetypeRow } from "./ecs/archetype/archetype";
export { ArchetypeService } from "./ecs/archetype/archetype-service";
export type { ComponentId, ComponentMeta } from "./ecs/component/component";
export { defineComponentMeta, getComponentMeta } from "./ecs/component/advanced";
export { Mask } from "./ecs/component/mask";
export { QueryService } from "./ecs/query/query-service";
export type { IArchetypeSource, IComponentResolver } from "./ecs/query/query";
export { UpdateStage } from "./schedule/stage";
export { Scheduler } from "./schedule/scheduler";
export type { SystemAccess, SystemDefinition } from "./schedule/system";
export { SystemSchedule, SystemScheduleBuilder } from "./schedule/schedule";
export type { SystemDependency } from "./schedule/schedule";
export { DevProfiler } from "./dev/profiler";
